[package]
name = "skytraxx-airspace-parser"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
description = "Parser for airspace files in Skytraxx format."
homepage = "https://github.com/dbrgn/skytraxx-airspace-parser/"
repository = "https://github.com/dbrgn/skytraxx-airspace-parser/"
readme = "README.md"
license = "MIT/Apache-2.0"
include = ["/src/**/*", "/tests/**/*", "/Cargo.toml", "/README.md", "/LICENSE-*"]
edition = "2018"

[dependencies]
log = "0.4"

[dev-dependencies]
env_logger = "0.6"
